# Generated by Django 6.1.1 on 2026-09-30 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0006_conversation_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Conversation',
            new_name='conversation',
        ),
    ]
