# Generated by Django 6.1.1 on 2026-09-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0007_rename_conversation_message_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('assistant', 'Assistant')], max_length=20),
        ),
    ]
