from pydantic import BaseModel
from typing import List

#define the expected structure of the AI reponse
class RAGResponse(BaseModel):
    #the actual answer generated by the AI
    answer: str

    #list of sources
    sources: list[str]

    #confidence level of the AI
    confidence: str

    #confidence level of the AI
    confidence: str